package gui.Studente;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.Controller;
import gui.Home;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class Int_RichiestaT extends JFrame {
    private transient Controller controller;
    private JPanel panel1;
    private JLabel COMPILARICHIESTALabel;
    private JComboBox LTDisponibiliComboBox;
    private JButton ReturnButton;
    private JButton logoutButton;
    private JButton RichiediButton;

    public Int_RichiestaT(Controller controller) {
        this.controller = controller;
        this.setContentPane(panel1);
        this.setTitle("RICHIESTA DI TIROCINIO");
        this.setSize(500, 350);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);


        logoutButton.addActionListener(e -> {
            Home NewHome = new Home(controller);
            NewHome.setVisible(true);
            this.dispose();
        });

        ReturnButton.addActionListener(e -> {
            Int_Studente interfacciaStud = new Int_Studente(controller);
            interfacciaStud.setVisible(true);
            this.dispose();
        });

        LTDisponibiliComboBox.removeAllItems();
        for (String idTirocinio : controller.visualizzaTirociniDisponibili()) {
            LTDisponibiliComboBox.addItem(idTirocinio);
        }

        RichiediButton.addActionListener(e -> {
            // 1. Controllo di sicurezza preventivo sulla ComboBox
            Object itemSelezionato = LTDisponibiliComboBox.getSelectedItem();
            if (itemSelezionato == null) {
                JOptionPane.showMessageDialog(this, "Seleziona un tirocinio prima di procedere.", "Attenzione", JOptionPane.WARNING_MESSAGE);
                return; // Interrompe l'esecuzione del metodo
            }

            try {
                // 2. Estrazione dell'ID dalla stringa ("15: Nome Tirocinio" -> 15)
                String tirocinioSelezionato = (String) itemSelezionato;

                // 3. Esecuzione della logica
                controller.compilaRichiesta(tirocinioSelezionato);
                JOptionPane.showMessageDialog(this, "Richiesta effettuata con successo");


                // 4. Ritorno alla schermata precedente
                Int_Studente interfacciaStud = new Int_Studente(controller);
                interfacciaStud.setVisible(true);
                this.dispose();

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Errore nella lettura dell'ID del tirocinio.", "Errore di formato", JOptionPane.ERROR_MESSAGE);
            } catch (IllegalStateException ex) {
                // Cattura l'eccezione se lo studente ha già una richiesta attiva (sollevata dal Controller)
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Errore", JOptionPane.ERROR_MESSAGE);
            }
        });


    }
    // region GUI designer generated Code
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-13467216));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-13467216));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-13467216));
        panel3.setForeground(new Color(-525825));
        panel2.add(panel3, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel3.setBorder(BorderFactory.createTitledBorder(null, "Lista Tirocini Disponibili", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-525825)));
        LTDisponibiliComboBox = new JComboBox();
        panel3.add(LTDisponibiliComboBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.add(panel4, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ReturnButton = new JButton();
        ReturnButton.setText("Torna alla Home");
        panel4.add(ReturnButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel5.setBackground(new Color(-13467216));
        panel2.add(panel5, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel5.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        RichiediButton = new JButton();
        RichiediButton.setText("Richiedi");
        panel5.add(RichiediButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel6.setBackground(new Color(-13610883));
        panel2.add(panel6, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        COMPILARICHIESTALabel = new JLabel();
        COMPILARICHIESTALabel.setBackground(new Color(-13610883));
        COMPILARICHIESTALabel.setForeground(new Color(-525825));
        COMPILARICHIESTALabel.setText("     \n\t\tCOMPILA RICHIESTA");
        panel6.add(COMPILARICHIESTALabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(230, 50), null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        panel6.add(logoutButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
