package gui.Studente;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.Controller;
import gui.Home;

import javax.swing.*;
import java.awt.*;

public class Int_Studente extends JFrame {
    Controller controller;
    private JPanel FinestraStudente;
    private JButton logoutButton;
    private JButton compilaRichiestaButton;
    private JButton caricaTesiButton;
    private JTextField statoTesiTextField;
    private JTextField StatoRichiestaTirocinio;
    private JTextField NomeCognomeS;
    private JLabel INTERFACCIAUTENTELabel;
    private JPanel asd;

    public Int_Studente(Controller controller) {
        this.controller = controller;
        $$$setupUI$$$();
        this.setContentPane(FinestraStudente);
        this.setTitle("INTERFACCIA STUDENTE");
        this.setSize(500, 350);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);


        NomeCognomeS.setText(controller.getstudLoggato().getNome() + " " + controller.getstudLoggato().getCognome());

        logoutButton.addActionListener(e -> {
            Home NewHome = new Home(controller);
            NewHome.setVisible(true);
            this.dispose();
        });


        //  - Compila Richiesta (istanzia l'oggetto)
        compilaRichiestaButton.addActionListener(e -> {
            String stato = controller.getStatoRichiesta(controller.getstudLoggato().getMatricola());
            try{
                if (stato.equals("In_attesa") ||stato.equals("Approvata") ){
                    JOptionPane.showMessageDialog(this, "ERRORE, impossibile inserire un ulteriore richiesta.");
                }

                else{
                    Int_RichiestaT IntRichiesta = new Int_RichiestaT(controller);
                    IntRichiesta.setVisible(true);
                    this.dispose();
                }
            }catch (NullPointerException exc){
                Int_RichiestaT IntRichiesta = new Int_RichiestaT(controller);
                IntRichiesta.setVisible(true);
                this.dispose();
            }

        });


        //  - Carica Tesi
        caricaTesiButton.addActionListener(e -> {
            Int_CaricaTesi IntCT = new Int_CaricaTesi(controller);
            IntCT.setVisible(true);
            this.dispose();
        });


        //  - Verifica Stato_Richiesta e Stato_tesi
        StatoRichiestaTirocinio.setText("Stato Richiesta Tirocinio : " + controller.getStatoRichiesta(controller.getMatricola()));
        statoTesiTextField.setText("Stato Tesi : " + controller.getStatoTesi(controller.getMatricola()));

    }
// region UI designer generated Code

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        FinestraStudente = new JPanel();
        FinestraStudente.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        FinestraStudente.setBackground(new Color(-13467216));
        panel1.add(FinestraStudente, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-13467216));
        FinestraStudente.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.add(panel3, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        compilaRichiestaButton = new JButton();
        compilaRichiestaButton.setText("Compila Richiesta");
        panel3.add(compilaRichiestaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.add(panel4, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        caricaTesiButton = new JButton();
        caricaTesiButton.setText("Carica Tesi");
        panel4.add(caricaTesiButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel5.setBackground(new Color(-13467216));
        panel2.add(panel5, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        statoTesiTextField = new JTextField();
        statoTesiTextField.setEditable(false);
        statoTesiTextField.setText("Stato Tesi : ");
        panel5.add(statoTesiTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        StatoRichiestaTirocinio = new JTextField();
        StatoRichiestaTirocinio.setEditable(false);
        StatoRichiestaTirocinio.setText("Stato Richiesta Tirocinio : ");
        panel5.add(StatoRichiestaTirocinio, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel6.setBackground(new Color(-13610883));
        panel2.add(panel6, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        NomeCognomeS = new JTextField();
        NomeCognomeS.setEditable(false);
        panel6.add(NomeCognomeS, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        panel6.add(logoutButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        INTERFACCIAUTENTELabel = new JLabel();
        INTERFACCIAUTENTELabel.setBackground(new Color(-13610883));
        INTERFACCIAUTENTELabel.setForeground(new Color(-525825));
        INTERFACCIAUTENTELabel.setText("\n         INTERFACCIA UTENTE");
        panel6.add(INTERFACCIAUTENTELabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(230, 50), null, 0, false));
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
    //endregion
}