package gui;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.Controller;
import gui.Docente.Int_Docente;
import gui.Registrazioni.Registrazione;
import gui.Studente.Int_Studente;
import gui.admin.Int_admin;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class Home extends JFrame {
	private transient Controller controller;
	private JButton LoginButton;
	private JTextField user;
	private JPanel finestra;
	private JButton RegisterButton;
	//i JRadioButton serviranno sia per la selezione del login che per quella della registrazione
	private JRadioButton studenteRadioButton;
	private JRadioButton docenteRadioButton;
	private JPasswordField passwordField1;
	private JTextField HOMETextField;
	private JTextArea textArea2;
	ButtonGroup gruppoScelte = new ButtonGroup();



	public Home(Controller controller) {
		this.controller = controller; // Assegna quello passato dall'esterno

		this.setContentPane(finestra);
		this.setTitle("PORTALE LOGIN");
		this.setSize(300, 400);
		this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		this.setLocationRelativeTo(null);
		gruppoScelte.add(studenteRadioButton);
		gruppoScelte.add(docenteRadioButton);


		LoginButton.addActionListener(e -> {
			String userInserito = this.user.getText();
			String passwordInserita = String.valueOf(this.passwordField1.getPassword());

			try {
				eseguiLogin(userInserito, passwordInserita);
			} catch (IllegalArgumentException ex) {
				JOptionPane.showMessageDialog(this, ex.getMessage(), "Accesso Negato", JOptionPane.ERROR_MESSAGE);
			}
		});

		RegisterButton.addActionListener(e -> {
			Registrazione reg = new Registrazione(this.controller);
			reg.setVisible(true);
			this.dispose();
		});

	}


	private void accessoStudente(String user, String pwd){
		boolean log = controller.effettuaLoginStudente(user, pwd);
		if (log) {
			Int_Studente interfacciaStud = new Int_Studente(this.controller);
			interfacciaStud.setVisible(true);
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(this, "Credenziali errate. Impossibile accedere", "Errore credenziali Studente", JOptionPane.WARNING_MESSAGE);
		}
	}


	private void accessoDocente(String user, String pwd){
		// Tenta il login come Docente, e nel caso apre l'interfaccia corrispondente
		boolean log = controller.effettuaLoginDocente(user, pwd);
		if (log) {
			Int_Docente interfacciaDoc = new Int_Docente(this.controller);
			interfacciaDoc.setVisible(true);
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(this, "Credenziali errate. Impossibile accedere", "Errore credenziali Docente", JOptionPane.WARNING_MESSAGE);
		}
	}

	private void accessoAdmin(String user, String pwd){
		boolean log = controller.effettuaLoginAdmin(user, pwd);
		if(log){
			Int_admin interfacciaAdmin = new Int_admin(this.controller);
			interfacciaAdmin.setVisible(true);
			this.dispose();
		}
		else
			JOptionPane.showMessageDialog(this, "Seleziona un ruolo (Studente o Docente) prima di accedere.", "JRadioButton Error 1", JOptionPane.WARNING_MESSAGE);
	}

	private void eseguiLogin(String user, String pwd) {
		if (studenteRadioButton.isSelected()) {
			accessoStudente(user, pwd);
		} else if (docenteRadioButton.isSelected()) {
			accessoDocente(user, pwd);
		} else {
			accessoAdmin(user, pwd);
		}
	}


//region GUI designer generated code

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		finestra = new JPanel();
		finestra.setLayout(new GridLayoutManager(6, 3, new Insets(0, 0, 0, 0), -1, -1));
		finestra.setBackground(new Color(-10054003));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel1.setBackground(new Color(-8675207));
		finestra.add(panel1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel2.setBackground(new Color(-9988467));
		panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		HOMETextField = new JTextField();
		HOMETextField.setBackground(new Color(-11637088));
		HOMETextField.setEditable(false);
		Font HOMETextFieldFont = this.$$$getFont$$$("Noto Sans Mandaic", Font.BOLD, 15, HOMETextField.getFont());
		if (HOMETextFieldFont != null) HOMETextField.setFont(HOMETextFieldFont);
		HOMETextField.setHorizontalAlignment(0);
		HOMETextField.setText("HOME");
		panel2.add(HOMETextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel3.setBackground(new Color(-1447188));
		finestra.add(panel3, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JPanel panel4 = new JPanel();
		panel4.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel4.setBackground(new Color(-2105372));
		panel3.add(panel4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JPanel panel5 = new JPanel();
		panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel5.setBackground(new Color(-1447188));
		panel5.setForeground(new Color(-723465));
		panel4.add(panel5, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		panel5.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Username", TitledBorder.LEFT, TitledBorder.TOP, this.$$$getFont$$$(null, -1, -1, panel5.getFont()), null));
		user = new JTextField();
		user.setBackground(new Color(-2105372));
		user.setInheritsPopupMenu(false);
		user.setText("");
		panel5.add(user, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 37), null, 0, false));
		final JPanel panel6 = new JPanel();
		panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel6.setBackground(new Color(-1447188));
		panel6.setForeground(new Color(-14935010));
		panel4.add(panel6, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		panel6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-3025959)), "Password", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
		passwordField1 = new JPasswordField();
		passwordField1.setBackground(new Color(-2105372));
		panel6.add(passwordField1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(200, 37), null, 0, false));
		final JPanel panel7 = new JPanel();
		panel7.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel7.setBackground(new Color(-2105372));
		panel7.setForeground(new Color(-2105372));
		panel4.add(panel7, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		panel7.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		final JPanel panel8 = new JPanel();
		panel8.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
		panel8.setBackground(new Color(-13146274));
		finestra.add(panel8, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		LoginButton = new JButton();
		LoginButton.setBackground(new Color(-16411031));
		Font LoginButtonFont = this.$$$getFont$$$("Plantagenet Cherokee", -1, -1, LoginButton.getFont());
		if (LoginButtonFont != null) LoginButton.setFont(LoginButtonFont);
		LoginButton.setForeground(new Color(-14935010));
		LoginButton.setHideActionText(false);
		LoginButton.setText("LOGIN");
		panel8.add(LoginButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		RegisterButton = new JButton();
		RegisterButton.setBackground(new Color(-16411031));
		Font RegisterButtonFont = this.$$$getFont$$$(".AppleSystemUIFont", -1, -1, RegisterButton.getFont());
		if (RegisterButtonFont != null) RegisterButton.setFont(RegisterButtonFont);
		RegisterButton.setForeground(new Color(-14935010));
		RegisterButton.setText("CREA ACCOUNT");
		panel8.add(RegisterButton, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		docenteRadioButton = new JRadioButton();
		docenteRadioButton.setBackground(new Color(-16411031));
		docenteRadioButton.setForeground(new Color(-14935010));
		docenteRadioButton.setOpaque(true);
		docenteRadioButton.setText("Docente");
		panel8.add(docenteRadioButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		studenteRadioButton = new JRadioButton();
		studenteRadioButton.setBackground(new Color(-16411031));
		studenteRadioButton.setBorderPainted(false);
		studenteRadioButton.setForeground(new Color(-14935010));
		studenteRadioButton.setHorizontalAlignment(4);
		studenteRadioButton.setMargin(new Insets(0, 1, 0, 1));
		studenteRadioButton.setOpaque(true);
		studenteRadioButton.setRequestFocusEnabled(true);
		studenteRadioButton.setRolloverEnabled(false);
		studenteRadioButton.setSelected(false);
		studenteRadioButton.setText("Studente");
		studenteRadioButton.setVerifyInputWhenFocusTarget(true);
		studenteRadioButton.setVerticalAlignment(0);
		panel8.add(studenteRadioButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer2 = new Spacer();
		finestra.add(spacer2, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		final JPanel panel9 = new JPanel();
		panel9.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		finestra.add(panel9, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		textArea2 = new JTextArea();
		textArea2.setBackground(new Color(-10054003));
		textArea2.setEditable(false);
		textArea2.setEnabled(true);
		panel9.add(textArea2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
		final Spacer spacer3 = new Spacer();
		finestra.add(spacer3, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		final Spacer spacer4 = new Spacer();
		finestra.add(spacer4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		final Spacer spacer5 = new Spacer();
		finestra.add(spacer5, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
		if (currentFont == null) return null;
		String resultName;
		if (fontName == null) {
			resultName = currentFont.getName();
		} else {
			Font testFont = new Font(fontName, Font.PLAIN, 10);
			if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
				resultName = fontName;
			} else {
				resultName = currentFont.getName();
			}
		}
		Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
		boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
		Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
		return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return finestra;
	}

}
