package gui.Docente;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.Controller;
import gui.Home;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;


public class Aggiunta_Argomenti extends JFrame {
    private transient Controller controller;
    private JTextField ArgTextField;
    private JButton AggiungiButton;
    private JButton RimuoviButton;
    private JComboBox<String> ArgComboBox;
    private JButton ReturnButton;
    private JPanel finestraArgomenti;
    private JButton logoutButton;
    private JLabel modificaListaArgomentiLabel;


    public Aggiunta_Argomenti(Controller controller) {
        this.controller = controller;
        this.setContentPane(finestraArgomenti);
        this.setTitle("AGGIUNTA ARGOMENTI");
        this.setSize(500, 300);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);

        ArgComboBox.removeAllItems();
        for (String arg : controller.getArgomentiDocLoggato()) {
            ArgComboBox.addItem(arg);
        }

        AggiungiButton.addActionListener(e -> {
            String Argomento = ArgTextField.getText();
            if (Argomento.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Inserire un argomento.", "Argomento Vuoto", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (controller.getdocLoggato().getListaArgomenti().contains(Argomento)) {
                JOptionPane.showMessageDialog(this, "Argomento già inserito.", "Argomento già presente", JOptionPane.WARNING_MESSAGE);
                return;
            }
            controller.aggiungiArgomenti(Argomento);
            ArgComboBox.addItem(Argomento);
            JOptionPane.showMessageDialog(this, "Argomento aggiunto con successo!");
        });


        RimuoviButton.addActionListener(e -> {
            try {
                String argomento = ArgComboBox.getSelectedItem().toString();
                controller.rimuoviArgomento(argomento);
                ArgComboBox.removeItem(argomento);
            } catch (NullPointerException exception) {
                JOptionPane.showMessageDialog(this, "Errore: Nessun argomento selezionato da rimuovere.", "Selezione vuota", JOptionPane.WARNING_MESSAGE);
            }
            JOptionPane.showMessageDialog(this, "Argomento rimosso con successo!");
        });

        ReturnButton.addActionListener(e -> {
            Int_Docente intDocente = new Int_Docente(controller);
            intDocente.setVisible(true);
            this.dispose();
        });
        logoutButton.addActionListener(e -> {
            Home NewHome = new Home(controller);
            NewHome.setVisible(true);
            this.dispose();
        });
    }

    //region GUI designer generated code

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        finestraArgomenti = new JPanel();
        finestraArgomenti.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1, true, false));
        finestraArgomenti.setBackground(new Color(-3245500));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-3245500));
        finestraArgomenti.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-3245500));
        panel2.setForeground(new Color(-525825));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(null, "Argomento", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-525825)));
        ArgTextField = new JTextField();
        ArgTextField.setText("");
        panel2.add(ArgTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        AggiungiButton = new JButton();
        AggiungiButton.setBackground(new Color(-8773859));
        AggiungiButton.setForeground(new Color(-16777216));
        AggiungiButton.setText("AGGIUNGI");
        panel2.add(AggiungiButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-3245500));
        panel1.add(panel3, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ReturnButton = new JButton();
        ReturnButton.setBackground(new Color(-8773859));
        ReturnButton.setForeground(new Color(-16777216));
        ReturnButton.setText("TORNA ALLA HOME");
        panel3.add(ReturnButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel4.setBackground(new Color(-3245500));
        panel1.add(panel4, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ArgComboBox = new JComboBox();
        ArgComboBox.setBackground(new Color(-3245500));
        panel4.add(ArgComboBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        RimuoviButton = new JButton();
        RimuoviButton.setBackground(new Color(-8773859));
        RimuoviButton.setForeground(new Color(-16777216));
        RimuoviButton.setText("RIMUOVI");
        panel4.add(RimuoviButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel5.setBackground(new Color(-9029114));
        panel1.add(panel5, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        panel5.add(logoutButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modificaListaArgomentiLabel = new JLabel();
        modificaListaArgomentiLabel.setBackground(new Color(-12314343));
        modificaListaArgomentiLabel.setForeground(new Color(-525825));
        modificaListaArgomentiLabel.setText("Modifica Lista Argomenti");
        panel5.add(modificaListaArgomentiLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return finestraArgomenti;
    }

}

