package gui.Docente;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.Controller;
import gui.Home;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDateTime;
import java.util.List;

public class Gestisci_Commissioni extends JFrame {
    Controller controller;
    private JPanel FinestraCommissioni;
    private JPanel FinestraSedute;
    private JButton ReturnButton;
    private JButton confermaButton;
    private JComboBox<String> SeduteCombobox;
    private JTable TabellaStudenti;
    private JButton logoutButton;
    private JLabel GESTISCICOMMISSIONELabel;
    private JPanel abdul;

    public Gestisci_Commissioni(Controller controller) {
        this.controller = controller;
        this.setContentPane(FinestraCommissioni);
        this.setTitle("GESTIONE COMMISSIONE");
        this.setSize(500, 600);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);


        String[] nomiColonne = {"Docente (Relatore)", "Studente", "Stato Tesi"};
        DefaultTableModel modelloTabella = new DefaultTableModel(nomiColonne, 0);
        TabellaStudenti.setModel(modelloTabella);


        List<String> seduteDisponibili = controller.getSeduteAperte();
        if (seduteDisponibili != null && !seduteDisponibili.isEmpty()) {
            for (String seduta : seduteDisponibili) {
                SeduteCombobox.addItem(seduta);
            }
        }


        SeduteCombobox.addActionListener(e -> {


            Object elementoSelezionato = SeduteCombobox.getSelectedItem();

            if (elementoSelezionato != null) {
                String sedutaScelta = elementoSelezionato.toString().split(":")[0].trim();
                int idSeduta = Integer.parseInt(sedutaScelta);

                DefaultTableModel model = (DefaultTableModel) TabellaStudenti.getModel();
                List<String[]> datiTabella = controller.getDatiTabellaSeduta(idSeduta);

                model.setRowCount(0);

                if (datiTabella != null) {
                    for (String[] riga : datiTabella) {
                        model.addRow(riga);
                    }
                }
            }
        });

        confermaButton.addActionListener(e -> {
            Object elementoSelezionato = SeduteCombobox.getSelectedItem();

            if (elementoSelezionato != null) {
                try {
                    // Passi la stringa al Controller (che farà split e ricerca)
                    int idSeduta = Integer.parseInt(elementoSelezionato.toString().split(":")[0].trim());
                    controller.confermaSeduta(idSeduta);

                    JOptionPane.showMessageDialog(this,
                            "Seduta confermata e chiusa con successo.",
                            "Seduta chiusa",
                            JOptionPane.INFORMATION_MESSAGE);

                } catch (IllegalArgumentException ex) {
                    // Intercetta l'errore "Seduta inesistente" o "Formato stringa non valido"
                    JOptionPane.showMessageDialog(this,
                            "Errore del sistema: " + ex.getMessage(),
                            "Errore",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });


        ReturnButton.addActionListener(e -> {
            Int_Docente interfacciaDoc = new Int_Docente(controller);
            interfacciaDoc.setVisible(true);
            this.dispose();
        });
        logoutButton.addActionListener(e -> {
            Home NewHome = new Home(controller);
            NewHome.setVisible(true);
            this.dispose();
        });


    }
    // region GUI designer generated Code
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        FinestraCommissioni = new JPanel();
        FinestraCommissioni.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        FinestraCommissioni.setBackground(new Color(-3245500));
        FinestraSedute = new JPanel();
        FinestraSedute.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        FinestraSedute.setBackground(new Color(-3245500));
        FinestraCommissioni.add(FinestraSedute, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-3245500));
        FinestraSedute.add(panel1, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ReturnButton = new JButton();
        ReturnButton.setBackground(new Color(-8773859));
        ReturnButton.setText("TORNA ALLA HOME");
        panel1.add(ReturnButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-3245500));
        FinestraSedute.add(panel2, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        confermaButton = new JButton();
        confermaButton.setText("Conferma");
        panel2.add(confermaButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-3245500));
        panel3.setForeground(new Color(-525825));
        FinestraSedute.add(panel3, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel3.setBorder(BorderFactory.createTitledBorder(null, "SEDUTE APERTE", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-525825)));
        SeduteCombobox = new JComboBox();
        panel3.add(SeduteCombobox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel4.setBackground(new Color(-11003379));
        FinestraSedute.add(panel4, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        panel4.add(logoutButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        GESTISCICOMMISSIONELabel = new JLabel();
        GESTISCICOMMISSIONELabel.setBackground(new Color(-12314343));
        GESTISCICOMMISSIONELabel.setForeground(new Color(-525825));
        GESTISCICOMMISSIONELabel.setText("GESTISCI COMMISSIONE");
        panel4.add(GESTISCICOMMISSIONELabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 50), null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        FinestraSedute.add(panel5, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setBackground(new Color(-3245500));
        scrollPane1.setForeground(new Color(-525825));
        panel5.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        TabellaStudenti = new JTable();
        TabellaStudenti.setAutoCreateColumnsFromModel(false);
        TabellaStudenti.setBackground(new Color(-3245500));
        TabellaStudenti.setForeground(new Color(-525825));
        TabellaStudenti.setGridColor(new Color(-3245500));
        TabellaStudenti.setName("TabellaStudentiJtable");
        TabellaStudenti.putClientProperty("JTable.autoStartsEdit", Boolean.FALSE);
        scrollPane1.setViewportView(TabellaStudenti);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return FinestraCommissioni;
    }
}
