package gui.Docente;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.Controller;
import gui.Home;

import javax.swing.*;
import java.awt.*;

public class Visualizza_R_Tir extends JFrame {
    Controller controller;
    private JButton ReturnButton;
    private JRadioButton approvaRadioButton;
    private JRadioButton rifiutaRadioButton;
    private JPanel VisTir;
    private JComboBox TirociniComboBox;
    private JComboBox StudentiComboBox;
    private JButton ValutaButton;
    private JButton logoutButton;
    private JTextArea textArea1;
    private JLabel RICHIESTEDITIROCINIOLabel;
    ButtonGroup gruppoScelte = new ButtonGroup();

    public Visualizza_R_Tir(Controller controller) {
        this.controller = controller;
        this.setContentPane(VisTir);
        this.setTitle("VALUTAZIONE RICHIESTE DI TIROCINIO");
        this.setSize(500, 300);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);

        gruppoScelte.add(approvaRadioButton);
        gruppoScelte.add(rifiutaRadioButton);

        // Aggiunta tirocini associati al docente loggato
        TirociniComboBox.removeAllItems();
        StudentiComboBox.removeAllItems();
        for (String nomeTir : controller.getNomiTirociniApertiDelDocente()) {
            TirociniComboBox.addItem(nomeTir);
        }


        // LISTENER COMBOBOX TIROCINI
        TirociniComboBox.addActionListener(e -> {

            if (TirociniComboBox.getSelectedItem() == null) {
                return;
            }

            // Estraiamo l'id dalla stringa, ci servirà per riconoscere l'oggetto selezionato al momento
            // del ritorno al controller per approvazione o rifiuto
            String tirocinioSelezionato = (String) TirociniComboBox.getSelectedItem();
            String idTirocinio = (String) tirocinioSelezionato.split(":")[0].trim();

            StudentiComboBox.removeAllItems(); // Pulisce gli studenti precedenti

             for (String matricola : controller.richiesteTir(tirocinioSelezionato)) {
                    StudentiComboBox.addItem(matricola);
                }
        });

        // LISTENER BOTTONE VALUTA
        ValutaButton.addActionListener(e -> {

            // Controlli di sicurezza
            if (TirociniComboBox.getSelectedItem() == null || StudentiComboBox.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Seleziona un tirocinio e uno studente.", "Dati mancanti", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Estrae i valori attuali
            String tirocinioSel = (String) TirociniComboBox.getSelectedItem();
            int idTirocinioSel = Integer.parseInt(tirocinioSel.split(":")[0].trim());
            String matricolaSel = (String) StudentiComboBox.getSelectedItem();


            // Approva o rifiuta a seconda del radiobutton selezionato
            if (approvaRadioButton.isSelected()) {
                controller.approvaRichiestaTirocinio(matricolaSel, idTirocinioSel);
            } else if (rifiutaRadioButton.isSelected()) {
                controller.rifiutaRichiestaTirocinio(matricolaSel, idTirocinioSel);
            } else {
                JOptionPane.showMessageDialog(this, "Seleziona Approvata o Rifiutata.", "Dati mancanti", JOptionPane.WARNING_MESSAGE);
                return;
            }
        });


        ReturnButton.addActionListener(e -> {
            Int_Docente interfacciaDoc = new Int_Docente(controller);
            interfacciaDoc.setVisible(true);
            this.dispose();
        });


        logoutButton.addActionListener(e -> {
            Home NewHome = new Home(controller);
            NewHome.setVisible(true);
            this.dispose();
        });

    }
    // region GUI designer generated Code
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        VisTir = new JPanel();
        VisTir.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        VisTir.setBackground(new Color(-3245500));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-3245500));
        VisTir.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setBackground(new Color(-3245500));
        panel1.add(panel2, new GridConstraints(5, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ReturnButton = new JButton();
        ReturnButton.setText("TORNA ALLA HOME");
        panel2.add(ReturnButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setBackground(new Color(-3245500));
        panel1.add(panel3, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ValutaButton = new JButton();
        ValutaButton.setBackground(new Color(-13255108));
        ValutaButton.setText("VALUTA");
        panel3.add(ValutaButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        approvaRadioButton = new JRadioButton();
        approvaRadioButton.setBackground(new Color(-525825));
        approvaRadioButton.setText("Approva");
        panel3.add(approvaRadioButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rifiutaRadioButton = new JRadioButton();
        rifiutaRadioButton.setBackground(new Color(-525825));
        rifiutaRadioButton.setText("Rifiuta");
        panel3.add(rifiutaRadioButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel4.setBackground(new Color(-3245500));
        panel1.add(panel4, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        TirociniComboBox = new JComboBox();
        TirociniComboBox.setBackground(new Color(-3245500));
        panel4.add(TirociniComboBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel5.setBackground(new Color(-3245500));
        panel1.add(panel5, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        StudentiComboBox = new JComboBox();
        StudentiComboBox.setBackground(new Color(-3245500));
        panel5.add(StudentiComboBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel6.setBackground(new Color(-9029114));
        panel1.add(panel6, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        logoutButton = new JButton();
        logoutButton.setText("Logout");
        panel6.add(logoutButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        RICHIESTEDITIROCINIOLabel = new JLabel();
        RICHIESTEDITIROCINIOLabel.setBackground(new Color(-9029114));
        RICHIESTEDITIROCINIOLabel.setForeground(new Color(-525825));
        RICHIESTEDITIROCINIOLabel.setText("RICHIESTE DI TIROCINIO ");
        panel6.add(RICHIESTEDITIROCINIOLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 50), null, 0, false));
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel7.setBackground(new Color(-3245500));
        panel1.add(panel7, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        textArea1 = new JTextArea();
        textArea1.setBackground(new Color(-3245500));
        textArea1.setEditable(false);
        panel7.add(textArea1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return VisTir;
    }
}
